<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Services\PostTemplate.html" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00017" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.10" />
		<PackageReference Include="SharpCompress" Version="0.41.0" />
	</ItemGroup>

</Project>
