<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Services\Implementation\PostTemplate.html" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Services\Implementation\PostTemplate.html" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.9" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
		<PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.9" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>				
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.10" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
		<PackageReference Include="System.Reactive" Version="6.1.0" />
		<PackageReference Include="WebViewControl-Avalonia" Version="3.120.10" />
		<PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00017" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.10" />
		<PackageReference Include="SharpCompress" Version="0.41.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Meziantou.Analyzer" Version="2.0.256">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
