<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>annotations</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00016" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="ReactiveUI.WPF" Version="18.4.1" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="7.0.0" />
    <PackageReference Include="Unity.Microsoft.DependencyInjection" Version="5.11.5" />
    <PackageReference Include="XZ.NET-netstandard" Version="2.0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Projects\tracker-search\src\TrackerOfflineSearch\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Services\Implementation\PostTemplate.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrackerOfflineSearch.Domain\TrackerOfflineSearch.Domain.csproj" />
  </ItemGroup>

</Project>
