<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PostTemplate.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PostTemplate.html" />
  </ItemGroup>

</Project>
