name: Build and Release

on:
  push:
    branches: [ main ]
    tags: ['v*']
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/TrackerOfflineSearch.sln

    - name: Build
      run: dotnet build ./src/TrackerOfflineSearch.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/TrackerOfflineSearch.sln --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"

    - name: Publish Test Results to GitHub
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx
        fail-on-error: false
      
    - name: Publish test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: "**/TestResults/*.trx"

    - name: Publish Linux
      run: dotnet publish ./src/TrackerOfflineSearch/TrackerOfflineSearch.csproj -c Release -r linux-x64 --self-contained true -o ./publish/linux-x64

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64-build
        path: publish/linux-x64/

    - name: Publish Windows
      run: dotnet publish ./src/TrackerOfflineSearch/TrackerOfflineSearch.csproj -c Release -r win-x64 --self-contained true -o ./publish/win-x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-x64-build
        path: publish/win-x64/

    - name: Publish OSX
      run: dotnet publish ./src/TrackerOfflineSearch/TrackerOfflineSearch.csproj -c Release -r osx-x64 --self-contained true -o ./publish/osx-x64

    - name: Upload OSX artifacts
      uses: actions/upload-artifact@v4
      with:
        name: osx-x64-build
        path: publish/osx-x64/
